# Generated by Django 5.1.6 on 2025-03-18 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0003_message_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='moodboard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moodboards.moodboard'),
            preserve_default=False,
        ),
    ]
