# Generated by Django 5.1.6 on 2025-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0004_rename_status_payment_payment_status_payment_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
