# Generated by Django 5.1.5 on 2025-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0007_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='CAtegory Description'),
            preserve_default=False,
        ),
    ]
