# Generated by Django 5.1.5 on 2025-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0008_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, choices=[('creator', 'Creator/Designer'), ('buyer', 'Buyer')], default='All', max_length=30),
        ),
    ]
