# Generated by Django 5.1.6 on 2025-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0013_alter_user_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='speciality',
            field=models.CharField(choices=[('All', 'All'), ('Seasonal Theme', 'Seasonal Theme'), ('Digital Design', 'Digital Design'), ('Photography', 'Photography'), ('Art & Illustration', 'Art & Illustration'), ('Branding & Marketing', 'Branding & Marketing'), ('Event Planning', 'Event Planning'), ('Fashion', 'Fashion'), ('Interior Design', 'Interior Design')], default='All', max_length=30),
        ),
    ]
