# Generated by Django 5.1.6 on 2025-03-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0018_remove_message_timestamp_message_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
