# Generated by Django 5.1.6 on 2025-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0020_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpeg', upload_to='profile_images/'),
        ),
    ]
